#!/usr/bin/env python3
"""Ingest a curated bibliography into screening.csv + atlas.csv.

Adds user-supplied references with include/exclude decisions, then appends
atlas contrasts for newly included priming/conditioning studies.
Idempotent on DOI / record_key / record_id.
"""
from __future__ import annotations

import csv
import re
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
SCREEN = ROOT / "data" / "screening" / "screening.csv"
ATLAS = ROOT / "data" / "atlas.csv"
VOCAB = ROOT / "data" / "schema" / "controlled_vocab.yaml"

TODAY = "2026-08-04"
EX = "biblio-ingest-v1"
SRC = "user-bibliography"

SCREEN_FIELDS = [
    "record_key", "doi", "first_author", "year", "title", "source",
    "decision", "exclude_reason", "maps_to_study_key", "screened_by", "notes",
]

# decision: include | exclude
# exclude_reason when exclude
BIBLIO: list[dict] = [
    # ---- INCLUDE: thermal hardening / thermotolerance ----
    dict(key="aleng2015", doi="10.1371/journal.pone.0135603", author="Aleng", year=2015,
         title="Non-lethal heat shock of the Asian green mussel, Perna viridis, promotes Hsp70 synthesis, induces thermotolerance and protects against Vibrio alginolyticus infection",
         decision="include", notes="heat hardening + cross-protection vs Vibrio"),
    dict(key="brown2004", doi="NR", author="Brown", year=2004,
         title="Thermotolerance and Hsp70 profiles in adult and embryonic California native oysters, Ostreola conchaphila",
         decision="include", notes="induced thermotolerance adult/embryo Olympia oyster"),
    dict(key="brun2009", doi="10.1016/j.jembe.2009.01.008", author="Brun", year=2009,
         title="Acquisition of thermotolerance in bay scallops, Argopecten irradians irradians, via differential induction of heat shock proteins",
         decision="include", notes="acquired thermotolerance via HSP induction"),
    dict(key="clegg1998", doi="NR", author="Clegg", year=1998,
         title="Induced thermotolerance and the heat shock protein-70 family in the Pacific oyster Crassostrea gigas",
         decision="include", notes="classic induced thermotolerance C. gigas"),
    dict(key="dong2023", doi="10.1016/j.scitotenv.2023.165785", author="Dong", year=2023,
         title="Transcriptome profiling reveals the strategy of thermal tolerance enhancement caused by heat-hardening in Mytilus coruscus",
         decision="include", notes="heat-hardening transcriptome Mytilus coruscus"),
    dict(key="dunphy2018", doi="10.1016/j.jtherbio.2018.03.006", author="Dunphy", year=2018,
         title="Metabolomic analysis of heat-hardening in adult green-lipped mussel (Perna canaliculus)",
         decision="include", notes="heat-hardening metabolomics Perna canaliculus"),
    dict(key="georgoulis2021", doi="10.1038/s41598-021-96617-9", author="Georgoulis", year=2021,
         title="Heat hardening enhances mitochondrial potential for respiration and oxidative defence capacity in the mantle of thermally stressed Mytilus galloprovincialis",
         decision="include", notes="heat hardening mitochondrial/oxidative defence"),
    dict(key="georgoulis2022", doi="10.1242/jeb.244795", author="Georgoulis", year=2022,
         title="Metabolic remodeling caused by heat hardening in the Mediterranean mussel Mytilus galloprovincialis",
         decision="include", notes="heat hardening metabolic remodeling"),
    dict(key="glass2023", doi="10.7717/peerj.16574", author="Glass", year=2023,
         title="Acute heat priming promotes short-term climate resilience of early life stages in a model sea anemone",
         decision="include", notes="acute heat priming early-life anemone"),
    dict(key="jackson2011", doi="10.1016/j.aquaculture.2011.04.015", author="Jackson", year=2011,
         title="Duration of induced thermal tolerance and tissue-specific expression of hsp/hsc70 in the eastern oyster, Crassostrea virginica and the pacific oyster, Crassostrea gigas",
         decision="include", notes="persistence window of induced thermal tolerance"),
    dict(key="moyen2020", doi="10.1098/rspb.2020.2561", author="Moyen", year=2020,
         title="A single heat-stress bout induces rapid and prolonged heat acclimation in the California mussel, Mytilus californianus",
         decision="include", notes="single-bout heat acclimation; prolonged persistence"),
    dict(key="song2024", doi="10.1016/j.aquaculture.2024.741169", author="Song", year=2024,
         title="Acquired thermotolerance in Crassostrea angulata: Effects of priming temperature, recovery temperature, and duration on survival and expression of HSP genes",
         decision="include", notes="dose/window of thermal priming explicit"),
    dict(key="zhang2021sync", doi="10.1111/1365-2435.13735", author="Zhang", year=2021,
         title="Synchronization of seasonal acclimatization and short-term heat hardening improves physiological resilience in a changing climate",
         decision="include", notes="heat hardening + seasonal acclimatization interaction"),
    dict(key="zhang2025", doi="10.1016/j.aquaculture.2024.741511", author="Zhang", year=2025,
         title="Heat hardening enhances the energy metabolism activity and oxidative defense ability of Manila clam Ruditapes philippinarum under different thermal stress",
         decision="include", notes="heat hardening Manila clam"),

    # ---- INCLUDE: immune priming ----
    dict(key="cong2008", doi="10.1016/j.cbpb.2008.06.012", author="Cong", year=2008,
         title="The enhanced immune protection of Zhikong scallop Chlamys farreri on the secondary encounter with Listonella anguillarum",
         decision="include", notes="within-gen immune priming scallop"),
    dict(key="cong2009", doi="10.1016/j.jip.2008.11.004", author="Cong", year=2009,
         title="The expression of peptidoglycan recognition protein-S1 gene in the scallop Chlamys farreri was enhanced after a second challenge by Listonella anguillarum",
         decision="include", notes="molecular readout of immune priming"),
    dict(key="fallet2022", doi="10.1186/s40168-022-01280-5", author="Fallet", year=2022,
         title="Early life microbial exposures shape the Crassostrea gigas immune system for lifelong and intergenerational disease protection",
         decision="include", notes="early-life microbial priming; lifelong + intergenerational"),
    dict(key="green2013", doi="10.1016/j.fsi.2013.04.034", author="Green", year=2013,
         title="Poly I:C induces a protective antiviral immune response in the Pacific oyster (Crassostrea gigas) against subsequent challenge with Ostreid herpesvirus (OsHV-1 muvar)",
         decision="include", notes="within-gen poly(I:C) antiviral priming"),
    dict(key="green2014", doi="10.1016/j.fsi.2014.05.036", author="Green", year=2014,
         title="Anti-viral gene induction is absent upon secondary challenge with double-stranded RNA in the Pacific oyster, Crassostrea gigas",
         decision="include", notes="secondary dsRNA challenge; reports absence of gene induction (negative molecular result)"),
    dict(key="green2016primed", doi="10.1016/j.molimm.2016.09.002", author="Green", year=2016,
         title="Primed for success: Oyster parents treated with poly(I:C) produce offspring with enhanced protection against Ostreid herpesvirus type I infection",
         decision="include", notes="parental poly(I:C) TGP; precursor to Lafont series"),
    dict(key="lafont2017", doi="10.1038/s41598-017-13364-6", author="Lafont", year=2017,
         title="Long-lasting antiviral innate immune priming in the Lophotrochozoan Pacific oyster, Crassostrea gigas",
         decision="include", notes="within-gen antiviral priming persists >=5 months"),
    dict(key="lafont2020", doi="10.1128/mBio.02777-19", author="Lafont", year=2020,
         title="A sustained immune response supports long-term antiviral immune priming in the Pacific oyster, Crassostrea gigas",
         decision="include", notes="mechanism of long-term antiviral priming"),
    dict(key="li2017", doi="10.1016/j.dci.2017.01.015", author="Li", year=2017,
         title="The hematopoiesis in gill and its role in the immune response of Pacific oyster Crassostrea gigas against secondary challenge with Vibrio splendidus",
         decision="include", notes="secondary Vibrio challenge / immune priming"),
    dict(key="morga2024", doi="10.3389/fmars.2024.1378511", author="Morga", year=2024,
         title="Antiviral protection in the Pacific oyster Crassostrea (Magallana) gigas against OsHV-1 infection using UV-inactivated virus",
         decision="include", notes="UV-inactivated virus as priming agent"),
    dict(key="reycampos2019", doi="10.3389/fimmu.2019.01894", author="Rey-Campos", year=2019,
         title="Immune tolerance in Mytilus galloprovincialis hemocytes after repeated contact with Vibrio splendidus",
         decision="include", notes="repeated pathogen contact; trained/tolerant immune phenotype"),
    dict(key="wang2013", doi="10.1016/j.dci.2013.02.003", author="Wang", year=2013,
         title="The response of mRNA expression upon secondary challenge with Vibrio anguillarum suggests the involvement of C-lectins in the immune priming of scallop Chlamys farreri",
         decision="include", notes="immune priming molecular markers scallop"),
    dict(key="wang2020", doi="10.1016/j.dci.2019.103498", author="Wang", year=2020,
         title="The involvement of TLR signaling and anti-bacterial effectors in enhanced immune protection of oysters after Vibrio splendidus pre-exposure",
         decision="include", notes="Vibrio pre-exposure enhances oyster antibacterial protection"),
    dict(key="yue2013", doi="10.1016/j.dci.2013.06.013", author="Yue", year=2013,
         title="Maternal transfer of immunity in scallop Chlamys farreri and its trans-generational immune protection to offspring against bacterial challenge",
         decision="include", notes="maternal/transgenerational immune protection"),
    dict(key="zhang2014", doi="10.1016/j.dci.2014.02.010", author="Zhang", year=2014,
         title="The specifically enhanced cellular immune responses in Pacific oyster (Crassostrea gigas) against secondary challenge with Vibrio splendidus",
         decision="include", notes="secondary Vibrio challenge cellular immune priming"),

    # ---- INCLUDE: OA / carryover / TGP / parental ----
    dict(key="alma2024", doi="10.3389/fmars.2024.1178507", author="Alma", year=2024,
         title="Phenotypic plasticity and carryover effects in an ecologically important bivalve in response to changing environments",
         decision="include", notes="bivalve carryover / plasticity under changing environments"),
    dict(key="fellous2022", doi="10.1111/gcb.15912", author="Fellous", year=2022,
         title="Windows of opportunity: Ocean warming shapes temperature-sensitive epigenetic reprogramming and gene expression across gametogenesis and embryogenesis in marine stickleback",
         decision="include", notes="warming windows across gametogenesis/embryogenesis; epigenetic"),
    dict(key="gurr2021", doi="10.1242/jeb.233932", author="Gurr", year=2021,
         title="Repeat exposure to hypercapnic seawater modifies growth and oxidative status in a tolerant burrowing clam",
         decision="include", notes="repeat hypercapnia = within-gen conditioning"),
    dict(key="gurr2019", doi="10.1101/773481", author="Gurr", year=2019,
         title="Metabolic recovery and compensatory shell growth of juvenile Pacific geoduck Panopea generosa following short-term exposure to acidified seawater",
         decision="include", notes="short-term OA exposure then recovery/carryover growth"),
    dict(key="hettinger2012", doi="10.1890/12-0567.1", author="Hettinger", year=2012,
         title="Persistent carry-over effects of planktonic exposure to ocean acidification in the Olympia oyster",
         decision="include", notes="larval OA carryover into juvenile; persists past metamorphosis"),
    dict(key="hettinger2013", doi="10.1111/gcb.12293", author="Hettinger", year=2013,
         title="Larval carry-over effects from ocean acidification persist in the natural environment",
         decision="include", notes="OA carryover persists in field post-metamorphosis"),
    dict(key="kozal2024", doi="10.3354/aei00472", author="Kozal", year=2024,
         title="Paternal heat exposure affects progeny larval development in green-lipped mussels Perna canaliculus",
         decision="include", notes="paternal thermal TGP"),
    dict(key="parker2024", doi="10.1016/j.marenvres.2024.106026", author="Parker", year=2024,
         title="Transgenerational plasticity responses differ across genetically distinct families in the Sydney rock oyster, Saccostrea glomerata",
         decision="include", notes="family-level variation in OA TGP"),
    dict(key="putnam2022", doi="10.1101/2022.06.24.497506", author="Putnam", year=2022,
         title="Dynamic DNA methylation contributes to carryover effects and beneficial acclimatization in geoduck clams",
         decision="include", notes="OA/pH conditioning; methylation + carryover geoduck"),
    dict(key="pereira2020", doi="10.1371/journal.pone.0228527", author="Pereira", year=2020,
         title="Can prior exposure to stress enhance resilience to ocean warming in two oyster species?",
         decision="include", notes="prior stress priming for warming resilience"),
    dict(key="rondon2017", doi="10.1093/eep/dvx004", author="Rondon", year=2017,
         title="Effects of a parental exposure to diuron on Pacific oyster spat methylome",
         decision="include", notes="parental pollutant → F1 methylome"),
    dict(key="spencer2019", doi="10.1002/eap.2060", author="Spencer", year=2019,
         title="Carryover effects of temperature and pCO2 across multiple Olympia oyster populations",
         decision="include", notes="developmental carryover temp + pCO2"),
    dict(key="waite2022", doi="10.1002/ecy.3565", author="Waite", year=2022,
         title="Negative carry-over effects on larval thermal tolerances across a natural thermal gradient",
         decision="include", notes="negative thermal carryover across natural gradient"),

    # ---- EXCLUDE: already in screening / reviews / not priming / plants / placeholders ----
    dict(key="beckers2007", doi="10.1016/j.pbi.2007.05.002", author="Beckers", year=2007,
         title="Priming for stress resistance: from the lab to the field", decision="exclude",
         reason="not-marine", notes="plant priming review"),
    dict(key="borges2022", doi="10.1086/722153", author="Borges", year=2022,
         title="Impacts of low oxygen on marine life: neglected, but a crucial priority for research",
         decision="exclude", reason="review", notes="priority/opinion piece"),
    dict(key="burge2014", doi="10.1146/annurev-marine-010213-135029", author="Burge", year=2014,
         title="Climate change influences on marine infectious diseases: implications for management and society",
         decision="exclude", reason="review"),
    dict(key="burrows2019", doi="10.1038/s41558-019-0631-5", author="Burrows", year=2019,
         title="Ocean community warming responses explained by thermal affinities and temperature gradients",
         decision="exclude", reason="not-priming", notes="community biogeography; no conditioning design"),
    dict(key="cheng2025", doi="xx.xxxx/placeholder", author="Cheng", year=2025,
         title="[Title unavailable – placeholder for Cheng et al. 2025]",
         decision="exclude", reason="not-priming", notes="placeholder citation; no extractable study"),
    dict(key="chevin2010", doi="10.1371/journal.pbio.1000357", author="Chevin", year=2010,
         title="Adaptation, plasticity, and extinction in a changing environment: towards a predictive theory",
         decision="exclude", reason="review", notes="theory/perspective"),
    dict(key="dang2023", doi="10.1016/j.envpol.2022.120813", author="Dang", year=2023,
         title="Wild oyster population resistance to ocean acidification adversely affected by bacterial infection",
         decision="exclude", reason="not-priming", notes="OA x infection interaction; not deliberate priming"),
    dict(key="downeywall2020", doi="10.3389/fmars.2020.566419", author="Downey-Wall", year=2020,
         title="Ocean acidification induces subtle shifts in gene expression and DNA methylation in mantle tissue of the eastern oyster",
         decision="exclude", reason="not-priming", notes="direct OA exposure omics; no prime-then-challenge design"),
    dict(key="duncan2014", doi="10.1002/jez.b.22571", author="Duncan", year=2014,
         title="Epigenetics, plasticity, and evolution: How do we link epigenetic change to phenotype?",
         decision="exclude", reason="review"),
    dict(key="durkin2025", doi="NR", author="Durkin", year=2025,
         title="Summary of Completed ceasmallr Work (Roberts Lab Notebook)",
         decision="exclude", reason="not-priming", notes="lab notebook post; not a primary paper"),
    dict(key="green2016distinct", doi="10.1186/s13567-016-0356-7", author="Green", year=2016,
         title="Distinct immune responses of juvenile and adult oysters (Crassostrea gigas) to viral and bacterial infections",
         decision="exclude", reason="not-priming", notes="age-dependent immune response; not a priming design"),
    dict(key="greenspeck2018", doi="10.3390/v10030133", author="Green", year=2018,
         title="Antiviral defense and innate immune memory in the oyster",
         decision="exclude", reason="review"),
    dict(key="hackerott2021", doi="10.1016/j.tree.2021.06.014", author="Hackerott", year=2021,
         title="Coral environmental memory: Causes, mechanisms, and consequences for future reefs",
         decision="exclude", reason="review"),
    dict(key="heli2018", doi="10.1016/j.tig.2018.07.006", author="He", year=2018,
         title="Epigenetic environmental memories in plants: Establishment, maintenance, and reprogramming",
         decision="exclude", reason="not-marine", notes="plants"),
    dict(key="hoffmann2011", doi="10.1038/nature09670", author="Hoffmann", year=2011,
         title="Climate change and evolutionary adaptation",
         decision="exclude", reason="review"),
    dict(key="hoegh2010", doi="10.1126/science.1189930", author="Hoegh-Guldberg", year=2010,
         title="The impact of climate change on the world's marine ecosystems",
         decision="exclude", reason="review"),
    dict(key="hilker2016", doi="10.1111/brv.12215", author="Hilker", year=2016,
         title="Priming and memory of stress responses in organisms lacking a nervous system",
         decision="exclude", reason="review"),
    dict(key="ivanina2013", doi="10.1016/j.aquatox.2013.10.019", author="Ivanina", year=2013,
         title="Interactive effects of pH and metals on mitochondrial functions of intertidal bivalves",
         decision="exclude", reason="not-priming", notes="interactive stress physiology; no priming design"),
    dict(key="iwasaki2014", doi="10.15252/embj.201488883", author="Iwasaki", year=2014,
         title="Epigenetic memory in plants",
         decision="exclude", reason="not-marine", notes="plants"),
    dict(key="kinoshita2014", doi="10.1093/pcp/pcu125", author="Kinoshita", year=2014,
         title="Epigenetic memory for stress response and adaptation in plants",
         decision="exclude", reason="not-marine", notes="plants"),
    dict(key="lim2020", doi="10.1016/j.marenvres.2020.105214", author="Lim", year=2020,
         title="DNA methylation changes in response to ocean acidification at the time of larval metamorphosis in the edible oyster, Crassostrea hongkongensis",
         decision="exclude", reason="not-priming", notes="OA exposure methylation at metamorphosis; no later challenge"),
    dict(key="liu2022", doi="xx.xxxx/placeholder", author="Liu", year=2022,
         title="[Title unavailable – placeholder for Liu et al. 2022]",
         decision="exclude", reason="not-priming", notes="placeholder citation"),
    dict(key="martins2020", doi="10.1128/mBio.00407-20", author="Martins", year=2020,
         title="Towards a mechanism for poly(I:C) antiviral priming in oysters",
         decision="exclude", reason="review", notes="commentary/perspective"),
    dict(key="masanja2023", doi="10.3389/fmars.2023.1159261", author="Masanja", year=2023,
         title="Impacts of marine heat extremes on bivalves",
         decision="exclude", reason="review"),
    dict(key="meehl2004", doi="10.1126/science.1098704", author="Meehl", year=2004,
         title="More intense, more frequent, and longer lasting heat waves in the 21st century",
         decision="exclude", reason="not-priming", notes="climate projection paper"),
    dict(key="montagnani2024", doi="10.1111/raq.12900", author="Montagnani", year=2024,
         title="Trained immunity: Perspectives for disease control strategy in marine mollusc aquaculture",
         decision="exclude", reason="review"),
    dict(key="munari2018", doi="10.1016/j.envpol.2018.05.005", author="Munari", year=2018,
         title="Does exposure to reduced pH and diclofenac induce oxidative stress in marine bivalves?",
         decision="exclude", reason="not-priming"),
    dict(key="petton2021", doi="10.3389/fimmu.2021.630343", author="Petton", year=2021,
         title="The Pacific oyster mortality syndrome, a polymicrobial and multifactorial disease: state of knowledge and future directions",
         decision="exclude", reason="review"),
    dict(key="rajan2021", doi="10.1111/gcb.15675", author="Rajan", year=2021,
         title="Oyster biomineralization under ocean acidification: From genes to shell",
         decision="exclude", reason="review"),
    dict(key="smale2019", doi="10.1038/s41558-019-0412-1", author="Smale", year=2019,
         title="Marine heatwaves threaten global biodiversity and the provision of ecosystem services",
         decision="exclude", reason="review"),
    dict(key="smith2023", doi="10.1146/annurev-marine-032122-121437", author="Smith", year=2023,
         title="Biological impacts of marine heatwaves",
         decision="exclude", reason="review"),
    dict(key="somero2010", doi="10.1242/jeb.037473", author="Somero", year=2010,
         title="The physiology of climate change: How potentials for acclimatization and genetic adaptation will determine winners and losers",
         decision="exclude", reason="review"),
    dict(key="somero2012", doi="10.1146/annurev-marine-120710-100935", author="Somero", year=2012,
         title="The physiology of global change: linking patterns to mechanisms",
         decision="exclude", reason="review"),
    dict(key="sommer2012", doi="10.1007/s00227-012-2081-8", author="Sommer", year=2012,
         title="The response of temperate aquatic ecosystems to global warming: Novel insights from a multidisciplinary project",
         decision="exclude", reason="review"),
    dict(key="steckbauer2020", doi="10.1111/gcb.15252", author="Steckbauer", year=2020,
         title="Additive impacts of deoxygenation and acidification threaten marine biota",
         decision="exclude", reason="not-priming"),
    dict(key="stevens2018", doi="10.3354/meps12725", author="Stevens", year=2018,
         title="Interactive effects of acidification, hypoxia, and thermal stress on growth, respiration, and survival of four North Atlantic bivalves",
         decision="exclude", reason="not-priming", notes="multi-stressor exposure; not priming design"),
    dict(key="venkataraman2020", doi="10.3389/fmars.2020.00225", author="Venkataraman", year=2020,
         title="General DNA methylation patterns and environmentally-induced differential methylation in the eastern oyster",
         decision="exclude", reason="not-priming", notes="OA methylation survey; no prime-then-challenge"),
    dict(key="venkataraman2022", doi="10.1186/s12864-022-08781-5", author="Venkataraman", year=2022,
         title="Differential DNA methylation in Pacific oyster reproductive tissue in response to ocean acidification",
         decision="exclude", reason="not-priming"),
    dict(key="venkataraman2024", doi="10.1093/eep/dvae018", author="Venkataraman", year=2024,
         title="DNA methylation correlates with transcriptional noise in response to elevated pCO2 in the eastern oyster",
         decision="exclude", reason="not-priming"),
    dict(key="waldbusser2010", doi="10.3354/meps08809", author="Waldbusser", year=2010,
         title="Size-dependent pH effect on calcification in post-larval hard clam Mercenaria spp.",
         decision="exclude", reason="not-priming"),
    dict(key="yang2021", doi="10.1016/j.aquaculture.2020.735831", author="Yang", year=2021,
         title="Immune priming in shellfish: A review and an updating mechanistic insight focused on cellular and humoral responses",
         decision="exclude", reason="review"),
    # already screened in prior pass (reaffirm / skip if present)
    dict(key="eirinlopez2019b", doi="10.1146/annurev-marine-010318-095114", author="Eirin-Lopez", year=2019,
         title="Marine environmental epigenetics", decision="exclude", reason="review",
         notes="already in screening"),
    dict(key="gavery2017b", doi="10.7717/peerj.4147", author="Gavery", year=2017,
         title="Epigenetic considerations in aquaculture", decision="exclude", reason="review",
         notes="already in screening"),
    dict(key="lafont2019dup", doi="10.1016/j.dci.2018.09.022", author="Lafont", year=2019,
         title="Transgenerational plasticity and antiviral immunity in the Pacific oyster against OsHV-1",
         decision="include", notes="same study as lafont2018 already extracted; screening alias only"),
]

# One (or few) contrast rows per newly included study. Grain: experimental contrast.
# Skip keys already fully covered in atlas (lafont2018/2019).
EXTRACT: list[dict] = [
    # thermal hardening cluster
    dict(record_id="aleng2015-01", study_key="aleng2015", doi="10.1371/journal.pone.0135603",
         first_author="Aleng", year=2015, short_title="Non-lethal heat shock induces thermotolerance and Vibrio protection in green mussel",
         species="Perna viridis", common_name="Asian green mussel", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="adult", life_stage_assayed="adult",
         priming_window_text="non-lethal heat shock", stressor_category="thermal",
         stressor_specific="non-lethal heat shock", environmentally_realistic="unclear",
         assay_type="survival", outcome_metric="thermotolerance / survival under subsequent heat",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="NA", methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="heat shock then thermal and Vibrio challenge", extraction_confidence="med",
         notes="also protects against Vibrio alginolyticus"),
    dict(record_id="aleng2015-02", study_key="aleng2015", doi="10.1371/journal.pone.0135603",
         first_author="Aleng", year=2015, short_title="Non-lethal heat shock induces thermotolerance and Vibrio protection in green mussel",
         species="Perna viridis", common_name="Asian green mussel", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="adult", life_stage_assayed="adult",
         priming_window_text="non-lethal heat shock", stressor_category="thermal",
         stressor_specific="non-lethal heat shock", environmentally_realistic="unclear",
         assay_type="immune-challenge", outcome_metric="protection against Vibrio alginolyticus",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="NA", methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="heat shock then pathogen challenge", extraction_confidence="med"),
    dict(record_id="clegg1998-01", study_key="clegg1998", doi="NR",
         first_author="Clegg", year=1998, short_title="Induced thermotolerance and HSP70 in C. gigas",
         species="Crassostrea gigas", common_name="Pacific oyster", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="adult", life_stage_assayed="adult",
         priming_window_text="sublethal heat shock", stressor_category="thermal",
         stressor_specific="sublethal heat shock", environmentally_realistic="unclear",
         assay_type="survival", outcome_metric="induced thermotolerance; HSP70 family induction",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="NA", methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="heat shock preconditioning", extraction_confidence="med"),
    dict(record_id="jackson2011-01", study_key="jackson2011", doi="10.1016/j.aquaculture.2011.04.015",
         first_author="Jackson", year=2011, short_title="Duration of induced thermal tolerance in C. virginica and C. gigas",
         species="Crassostrea gigas", common_name="Pacific oyster", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="adult", life_stage_assayed="adult",
         priming_window_text="induced thermal tolerance protocol; duration tracked",
         stressor_category="thermal", stressor_specific="sublethal heat shock",
         environmentally_realistic="unclear",
         assay_type="survival", outcome_metric="duration of induced thermal tolerance; tissue HSP/HSC70",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persistence_unit="days", latest_timepoint_assayed="post-hardening time series",
         persisted_past_metamorphosis="NA",
         persistence_notes="explicitly measures how long induced thermotolerance lasts",
         methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="heat hardening with temporal decay assay; two oyster species", extraction_confidence="med"),
    dict(record_id="brun2009-01", study_key="brun2009", doi="10.1016/j.jembe.2009.01.008",
         first_author="Brun", year=2009, short_title="Acquisition of thermotolerance in bay scallops via HSPs",
         species="Argopecten irradians", common_name="bay scallop", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="adult", life_stage_assayed="adult",
         priming_window_text="heat shock preconditioning", stressor_category="thermal",
         stressor_specific="heat shock", environmentally_realistic="unclear",
         assay_type="survival", outcome_metric="acquired thermotolerance via differential HSP induction",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="NA", methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="heat shock then lethal thermal challenge", extraction_confidence="med"),
    dict(record_id="brown2004-01", study_key="brown2004", doi="NR",
         first_author="Brown", year=2004, short_title="Thermotolerance and HSP70 in Olympia oyster adult and embryo",
         species="Ostrea lurida", common_name="Olympia oyster", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="adult", life_stage_assayed="adult",
         priming_window_text="thermal challenge / HSP70 profiling adult and embryo",
         stressor_category="thermal", stressor_specific="heat stress", environmentally_realistic="yes",
         assay_type="physiology-other", outcome_metric="thermotolerance and HSP70 profiles",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="not-tested", methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="thermotolerance assays adult vs embryo", extraction_confidence="low",
         notes="species listed historically as Ostreola conchaphila"),
    dict(record_id="dong2023-01", study_key="dong2023", doi="10.1016/j.scitotenv.2023.165785",
         first_author="Dong", year=2023, short_title="Heat-hardening enhances thermal tolerance in Mytilus coruscus",
         species="Mytilus coruscus", common_name="hard-shelled mussel", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="adult", life_stage_assayed="adult",
         priming_window_text="heat-hardening treatment", stressor_category="thermal",
         stressor_specific="heat-hardening", environmentally_realistic="yes",
         assay_type="transcriptome", outcome_metric="transcriptome strategy of enhanced thermal tolerance",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="NA", methylation_measured="no", transcriptome_measured="yes", ncRNA_measured="no",
         study_design="heat-hardening then thermal stress + RNA-seq", extraction_confidence="med"),
    dict(record_id="dunphy2018-01", study_key="dunphy2018", doi="10.1016/j.jtherbio.2018.03.006",
         first_author="Dunphy", year=2018, short_title="Heat-hardening metabolomics in green-lipped mussel",
         species="Perna canaliculus", common_name="green-lipped mussel", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="adult", life_stage_assayed="adult",
         priming_window_text="heat-hardening", stressor_category="thermal",
         stressor_specific="heat-hardening", environmentally_realistic="yes",
         assay_type="physiology-other", outcome_metric="metabolomic signature (succinate; GABAergic pathway)",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="NA", methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="heat-hardening metabolomics", extraction_confidence="med"),
    dict(record_id="georgoulis2021-01", study_key="georgoulis2021", doi="10.1038/s41598-021-96617-9",
         first_author="Georgoulis", year=2021, short_title="Heat hardening enhances mitochondrial/oxidative defence in M. galloprovincialis",
         species="Mytilus galloprovincialis", common_name="Mediterranean mussel", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="adult", life_stage_assayed="adult",
         priming_window_text="heat hardening then thermal stress", stressor_category="thermal",
         stressor_specific="heat hardening", environmentally_realistic="yes",
         assay_type="physiology-other", outcome_metric="mitochondrial respiration and oxidative defence capacity",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="NA", methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="heat hardening + thermal stress physiology", extraction_confidence="med"),
    dict(record_id="georgoulis2022-01", study_key="georgoulis2022", doi="10.1242/jeb.244795",
         first_author="Georgoulis", year=2022, short_title="Metabolic remodeling by heat hardening in M. galloprovincialis",
         species="Mytilus galloprovincialis", common_name="Mediterranean mussel", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="adult", life_stage_assayed="adult",
         priming_window_text="heat hardening", stressor_category="thermal",
         stressor_specific="heat hardening", environmentally_realistic="yes",
         assay_type="physiology-other", outcome_metric="metabolic remodeling under heat hardening",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="NA", methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="heat hardening metabolomics/physiology", extraction_confidence="med"),
    dict(record_id="moyen2020-01", study_key="moyen2020", doi="10.1098/rspb.2020.2561",
         first_author="Moyen", year=2020, short_title="Single heat-stress bout induces prolonged heat acclimation in M. californianus",
         species="Mytilus californianus", common_name="California mussel", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="adult", life_stage_assayed="adult",
         priming_window_text="single heat-stress bout", stressor_category="thermal",
         stressor_specific="single heat-stress bout", environmentally_realistic="yes",
         assay_type="physiology-other", outcome_metric="rapid and prolonged heat acclimation",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persistence_unit="days", latest_timepoint_assayed="prolonged post-bout window",
         persisted_past_metamorphosis="NA",
         persistence_notes="emphasizes prolonged persistence after a single bout",
         methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="single bout then repeated thermal performance assays", extraction_confidence="med"),
    dict(record_id="song2024-01", study_key="song2024", doi="10.1016/j.aquaculture.2024.741169",
         first_author="Song", year=2024, short_title="Acquired thermotolerance priming windows in C. angulata",
         species="Crassostrea angulata", common_name="Portuguese oyster", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="adult", life_stage_assayed="adult",
         priming_window_text="factorial priming temperature x recovery temperature x duration",
         stressor_category="thermal", stressor_specific="thermal priming / acquired thermotolerance",
         environmentally_realistic="yes",
         assay_type="survival", outcome_metric="survival and HSP gene expression after priming",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="NA",
         persistence_notes="explicitly varies priming and recovery duration (dose/window study)",
         methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="priming temp x recovery temp x duration factorial", extraction_confidence="med",
         notes="Section-6 exemplar: identify windows and doses"),
    dict(record_id="zhang2025-01", study_key="zhang2025", doi="10.1016/j.aquaculture.2024.741511",
         first_author="Zhang", year=2025, short_title="Heat hardening enhances metabolism/oxidative defence in Manila clam",
         species="Ruditapes philippinarum", common_name="Manila clam", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="adult", life_stage_assayed="adult",
         priming_window_text="heat hardening then thermal stress", stressor_category="thermal",
         stressor_specific="heat hardening", environmentally_realistic="yes",
         assay_type="physiology-other", outcome_metric="energy metabolism and oxidative defense under thermal stress",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="NA", methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="heat hardening + graded thermal stress", extraction_confidence="med"),
    dict(record_id="zhang2021sync-01", study_key="zhang2021sync", doi="10.1111/1365-2435.13735",
         first_author="Zhang", year=2021, short_title="Seasonal acclimatization synced with heat hardening improves resilience",
         species="NR", common_name="NR", taxon_group="other", taxon_class="NR",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="adult", life_stage_assayed="adult",
         priming_window_text="short-term heat hardening combined with seasonal acclimatization",
         stressor_category="thermal", stressor_specific="heat hardening + seasonal acclimatization",
         environmentally_realistic="yes",
         assay_type="physiology-other", outcome_metric="physiological resilience under climate-relevant heat",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="NA", methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="seasonal acclimatization x heat hardening", extraction_confidence="low",
         notes="species to confirm on full text; Functional Ecology 2021"),

    # immune priming
    dict(record_id="green2013-01", study_key="green2013", doi="10.1016/j.fsi.2013.04.034",
         first_author="Green", year=2013, short_title="Poly(I:C) protects C. gigas against subsequent OsHV-1 challenge",
         species="Crassostrea gigas", common_name="Pacific oyster", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="adult", life_stage_assayed="adult",
         priming_window_text="poly(I:C) then OsHV-1 muvar challenge",
         stressor_category="pathogen-immune", stressor_specific="poly(I:C)",
         environmentally_realistic="no",
         assay_type="immune-challenge", outcome_metric="survival / viral load after OsHV-1 challenge",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="NA", methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="poly(I:C) prime then viral challenge", extraction_confidence="med"),
    dict(record_id="green2016primed-01", study_key="green2016primed", doi="10.1016/j.molimm.2016.09.002",
         first_author="Green", year=2016, short_title="Parental poly(I:C) doubles larval survival to OsHV-1",
         species="Crassostrea gigas", common_name="Pacific oyster", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F1", transmission_channel="biparental",
         life_stage_primed="gamete-broodstock", life_stage_assayed="veliger-larva",
         priming_window_text="parents treated with poly(I:C) before spawning",
         stressor_category="pathogen-immune", stressor_specific="poly(I:C)",
         environmentally_realistic="no",
         assay_type="immune-challenge", outcome_metric="D-veliger survival after OsHV-1; elevated IRF2 mRNA",
         effect_direction="beneficial", effect_size_type="odds-ratio", significance="sig",
         latest_timepoint_assayed="D-veliger larvae", persisted_past_metamorphosis="not-tested",
         persistence_notes="TGEP at larval stage; persistence past metamorphosis not tested here",
         methylation_measured="no", transcriptome_measured="yes", ncRNA_measured="no",
         study_design="parental poly(I:C) then larval viral challenge", extraction_confidence="high",
         notes="framework Section-6 poly(I:C) broodstock precedent"),
    dict(record_id="lafont2017-01", study_key="lafont2017", doi="10.1038/s41598-017-13364-6",
         first_author="Lafont", year=2017, short_title="Long-lasting antiviral innate immune priming in C. gigas",
         species="Crassostrea gigas", common_name="Pacific oyster", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="adult", life_stage_assayed="adult",
         priming_window_text="poly(I:C)/dsRNA priming; protection re-tested over months",
         stressor_category="pathogen-immune", stressor_specific="poly(I:C)",
         environmentally_realistic="no",
         assay_type="immune-challenge", outcome_metric="antiviral protection duration after priming",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persistence_value=5, persistence_unit="months",
         latest_timepoint_assayed=">=5 months post-prime",
         persisted_past_metamorphosis="NA",
         persistence_notes="protection persists at least 5 months within generation",
         methylation_measured="no", transcriptome_measured="yes", ncRNA_measured="no",
         study_design="prime then time-lagged OsHV-1 challenge", extraction_confidence="high"),
    dict(record_id="lafont2020-01", study_key="lafont2020", doi="10.1128/mBio.02777-19",
         first_author="Lafont", year=2020, short_title="Sustained immune response supports long-term antiviral priming",
         species="Crassostrea gigas", common_name="Pacific oyster", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="adult", life_stage_assayed="adult",
         priming_window_text="antiviral immune priming with sustained response",
         stressor_category="pathogen-immune", stressor_specific="poly(I:C) / antiviral priming",
         environmentally_realistic="no",
         assay_type="immune-challenge", outcome_metric="long-term antiviral primed state / sustained immune markers",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persistence_unit="months", persisted_past_metamorphosis="NA",
         methylation_measured="no", transcriptome_measured="yes", ncRNA_measured="no",
         study_design="mechanistic follow-up of long-term priming", extraction_confidence="med"),
    dict(record_id="fallet2022-01", study_key="fallet2022", doi="10.1186/s40168-022-01280-5",
         first_author="Fallet", year=2022, short_title="Early-life microbes shape lifelong and intergenerational oyster disease protection",
         species="Crassostrea gigas", common_name="Pacific oyster", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0-F1", transmission_channel="maternal",
         life_stage_primed="embryo", life_stage_assayed="adult",
         priming_window_text="early-life microbial exposures",
         stressor_category="pathogen-immune", stressor_specific="early-life microbial community exposure",
         environmentally_realistic="yes",
         assay_type="immune-challenge", outcome_metric="lifelong and intergenerational disease protection",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persistence_unit="years", latest_timepoint_assayed="adult + next generation",
         persisted_past_metamorphosis="yes",
         persistence_notes="protection lasts lifelong within gen and transmits intergenerationally",
         methylation_measured="no", transcriptome_measured="yes", ncRNA_measured="no",
         study_design="early-life microbial exposure; disease challenge across life and generation",
         extraction_confidence="med"),
    dict(record_id="morga2024-01", study_key="morga2024", doi="10.3389/fmars.2024.1378511",
         first_author="Morga", year=2024, short_title="UV-inactivated OsHV-1 primes antiviral protection in C. gigas",
         species="Crassostrea gigas", common_name="Pacific oyster", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="spat-juvenile", life_stage_assayed="spat-juvenile",
         priming_window_text="UV-inactivated OsHV-1 exposure then virulent challenge",
         stressor_category="pathogen-immune", stressor_specific="UV-inactivated OsHV-1",
         environmentally_realistic="no",
         assay_type="immune-challenge", outcome_metric="antiviral protection / survival after virulent OsHV-1",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="NA", methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="inactivated-virus prime then challenge", extraction_confidence="med"),
    dict(record_id="cong2008-01", study_key="cong2008", doi="10.1016/j.cbpb.2008.06.012",
         first_author="Cong", year=2008, short_title="Enhanced immune protection on secondary Listonella challenge in scallop",
         species="Chlamys farreri", common_name="Zhikong scallop", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="adult", life_stage_assayed="adult",
         priming_window_text="primary then secondary Listonella anguillarum encounter",
         stressor_category="pathogen-immune", stressor_specific="Listonella anguillarum",
         environmentally_realistic="yes",
         assay_type="immune-challenge", outcome_metric="enhanced immune protection on secondary encounter",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="NA", methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="prime-challenge immune priming", extraction_confidence="med"),
    dict(record_id="yue2013-01", study_key="yue2013", doi="10.1016/j.dci.2013.06.013",
         first_author="Yue", year=2013, short_title="Maternal transfer of immunity protects scallop offspring",
         species="Chlamys farreri", common_name="Zhikong scallop", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F1", transmission_channel="maternal",
         life_stage_primed="gamete-broodstock", life_stage_assayed="veliger-larva",
         priming_window_text="maternal immune stimulation; offspring bacterial challenge",
         stressor_category="pathogen-immune", stressor_specific="bacterial challenge (maternal priming)",
         environmentally_realistic="yes",
         assay_type="immune-challenge", outcome_metric="transgenerational immune protection of offspring",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="not-tested", methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="maternal priming then offspring bacterial challenge", extraction_confidence="med"),
    dict(record_id="zhang2014-01", study_key="zhang2014", doi="10.1016/j.dci.2014.02.010",
         first_author="Zhang", year=2014, short_title="Enhanced cellular immunity on secondary Vibrio challenge in C. gigas",
         species="Crassostrea gigas", common_name="Pacific oyster", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="adult", life_stage_assayed="adult",
         priming_window_text="primary then secondary Vibrio splendidus challenge",
         stressor_category="pathogen-immune", stressor_specific="Vibrio splendidus",
         environmentally_realistic="yes",
         assay_type="immune-challenge", outcome_metric="specifically enhanced cellular immune responses",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="NA", methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="secondary challenge immune priming", extraction_confidence="med"),
    dict(record_id="wang2020-01", study_key="wang2020", doi="10.1016/j.dci.2019.103498",
         first_author="Wang", year=2020, short_title="Vibrio splendidus pre-exposure enhances oyster antibacterial protection",
         species="Crassostrea gigas", common_name="Pacific oyster", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="adult", life_stage_assayed="adult",
         priming_window_text="Vibrio splendidus pre-exposure then challenge",
         stressor_category="pathogen-immune", stressor_specific="Vibrio splendidus pre-exposure",
         environmentally_realistic="yes",
         assay_type="immune-challenge", outcome_metric="TLR signaling / antibacterial effectors; enhanced protection",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="NA", methylation_measured="no", transcriptome_measured="yes", ncRNA_measured="no",
         study_design="pre-exposure then bacterial challenge", extraction_confidence="med"),
    dict(record_id="reycampos2019-01", study_key="reycampos2019", doi="10.3389/fimmu.2019.01894",
         first_author="Rey-Campos", year=2019, short_title="Immune tolerance after repeated Vibrio contact in mussel hemocytes",
         species="Mytilus galloprovincialis", common_name="Mediterranean mussel", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="adult", life_stage_assayed="adult",
         priming_window_text="repeated contact with Vibrio splendidus",
         stressor_category="pathogen-immune", stressor_specific="Vibrio splendidus repeated exposure",
         environmentally_realistic="yes",
         assay_type="immune-challenge", outcome_metric="hemocyte immune tolerance / trained phenotype",
         effect_direction="mixed", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="NA", methylation_measured="no", transcriptome_measured="yes", ncRNA_measured="no",
         study_design="repeated pathogen contact", extraction_confidence="med",
         notes="tolerance vs classical enhanced priming; still a memory phenotype"),

    # OA / carryover / TGP
    dict(record_id="hettinger2012-01", study_key="hettinger2012", doi="10.1890/12-0567.1",
         first_author="Hettinger", year=2012, short_title="Persistent larval OA carryover in Olympia oyster past metamorphosis",
         species="Ostrea lurida", common_name="Olympia oyster", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="veliger-larva", life_stage_assayed="spat-juvenile",
         priming_window_text="planktonic larval exposure to ocean acidification",
         stressor_category="OA-low-pH", stressor_specific="larval ocean acidification exposure",
         environmentally_realistic="yes",
         assay_type="growth-size", outcome_metric="persistent carry-over effects into juvenile performance",
         effect_direction="costly", effect_size_type="NR", significance="sig",
         latest_timepoint_assayed="post-metamorphic juveniles",
         persisted_past_metamorphosis="yes",
         persistence_notes="larval OA exposure effects persist after metamorphosis",
         methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="larval OA exposure then juvenile assays", extraction_confidence="high",
         notes="flagship: bivalve larval priming, sticks past metamorphosis"),
    dict(record_id="hettinger2013-01", study_key="hettinger2013", doi="10.1111/gcb.12293",
         first_author="Hettinger", year=2013, short_title="Larval OA carryover persists in the natural environment",
         species="Ostrea lurida", common_name="Olympia oyster", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="veliger-larva", life_stage_assayed="spat-juvenile",
         priming_window_text="larval OA then outplant to field",
         stressor_category="OA-low-pH", stressor_specific="larval ocean acidification exposure",
         environmentally_realistic="yes",
         assay_type="survival", outcome_metric="field juvenile performance after larval OA",
         effect_direction="costly", effect_size_type="NR", significance="sig",
         latest_timepoint_assayed="field juveniles",
         persisted_past_metamorphosis="yes",
         persistence_notes="carryover persists under natural environmental conditions",
         methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="lab larval OA then field deployment", extraction_confidence="high"),
    dict(record_id="spencer2019-01", study_key="spencer2019", doi="10.1002/eap.2060",
         first_author="Spencer", year=2019, short_title="Carryover of temperature and pCO2 across Olympia oyster populations",
         species="Ostrea lurida", common_name="Olympia oyster", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="veliger-larva", life_stage_assayed="spat-juvenile",
         priming_window_text="early-life temperature and pCO2 treatments across populations",
         stressor_category="multiple", stressor_specific="temperature + elevated pCO2",
         environmentally_realistic="yes",
         assay_type="growth-size", outcome_metric="carryover effects on later performance across populations",
         effect_direction="mixed", effect_size_type="NR", significance="sig",
         latest_timepoint_assayed="juveniles", persisted_past_metamorphosis="yes",
         methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="multi-population developmental carryover", extraction_confidence="med"),
    dict(record_id="pereira2020-01", study_key="pereira2020", doi="10.1371/journal.pone.0228527",
         first_author="Pereira", year=2020, short_title="Prior stress exposure and warming resilience in two oyster species",
         species="Saccostrea glomerata", common_name="Sydney rock oyster", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="spat-juvenile", life_stage_assayed="spat-juvenile",
         priming_window_text="prior stress exposure then ocean warming challenge",
         stressor_category="thermal", stressor_specific="prior stress priming for warming",
         dose_text="prior stress then warming; two oyster species",
         environmentally_realistic="yes",
         assay_type="survival", outcome_metric="resilience to ocean warming after prior stress",
         effect_direction="mixed", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="NA", methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="prior stress x warming; two species", extraction_confidence="med",
         notes="also includes a second oyster species in the paper"),
    dict(record_id="gurr2021-01", study_key="gurr2021", doi="10.1242/jeb.233932",
         first_author="Gurr", year=2021, short_title="Repeat hypercapnia modifies growth/oxidative status in burrowing clam",
         species="Leukoma staminea", common_name="Pacific littleneck clam", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="spat-juvenile", life_stage_assayed="spat-juvenile",
         priming_window_text="repeat exposure to hypercapnic seawater",
         stressor_category="OA-low-pH", stressor_specific="repeat hypercapnia",
         environmentally_realistic="yes",
         assay_type="growth-size", outcome_metric="growth and oxidative status after repeated hypercapnia",
         effect_direction="mixed", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="NA", methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="repeat vs single hypercapnia exposure", extraction_confidence="med",
         notes="confirm species on full text if needed"),
    dict(record_id="putnam2022-01", study_key="putnam2022", doi="10.1101/2022.06.24.497506",
         first_author="Putnam", year=2022, short_title="Dynamic DNA methylation contributes to carryover and beneficial acclimatization in geoduck",
         species="Panopea generosa", common_name="Pacific geoduck", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="spat-juvenile", life_stage_assayed="spat-juvenile",
         priming_window_text="environmental conditioning with methylation dynamics",
         stressor_category="OA-low-pH", stressor_specific="acidified / altered carbonate chemistry conditioning",
         environmentally_realistic="yes",
         assay_type="methylation", outcome_metric="dynamic DNA methylation linked to carryover and beneficial acclimatization",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="NA",
         methylation_measured="yes", methylation_method="other", transcriptome_measured="no", ncRNA_measured="no",
         study_design="conditioning with methylome + performance carryover", extraction_confidence="med",
         notes="bioRxiv preprint"),
    dict(record_id="rondon2017-01", study_key="rondon2017", doi="10.1093/eep/dvx004",
         first_author="Rondon", year=2017, short_title="Parental diuron exposure alters Pacific oyster spat methylome",
         species="Crassostrea gigas", common_name="Pacific oyster", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F1", transmission_channel="biparental",
         life_stage_primed="gamete-broodstock", life_stage_assayed="spat-juvenile",
         priming_window_text="parental diuron exposure; spat methylome assayed",
         stressor_category="pollutant", stressor_specific="diuron",
         environmentally_realistic="yes",
         assay_type="methylation", outcome_metric="F1 spat methylome shifts after parental diuron",
         effect_direction="mixed", effect_size_type="NR", significance="sig",
         latest_timepoint_assayed="spat", persisted_past_metamorphosis="yes",
         persistence_notes="parental exposure signature detected in post-metamorphic spat methylome",
         methylation_measured="yes", methylation_method="RRBS-Methyl-seq", transcriptome_measured="no", ncRNA_measured="no",
         study_design="parental pollutant exposure; F1 methylome", extraction_confidence="med"),
    dict(record_id="parker2024-01", study_key="parker2024", doi="10.1016/j.marenvres.2024.106026",
         first_author="Parker", year=2024, short_title="OA TGP differs across genetically distinct S. glomerata families",
         species="Saccostrea glomerata", common_name="Sydney rock oyster", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F1", transmission_channel="biparental",
         life_stage_primed="gamete-broodstock", life_stage_assayed="veliger-larva",
         priming_window_text="parental OA; family-structured TGP",
         stressor_category="OA-low-pH", stressor_specific="ocean acidification",
         environmentally_realistic="yes",
         assay_type="physiology-other", outcome_metric="TGP magnitude differs among genetically distinct families",
         effect_direction="mixed", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="not-tested", methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="family-level TGP under OA", extraction_confidence="med"),
    dict(record_id="alma2024-01", study_key="alma2024", doi="10.3389/fmars.2024.1178507",
         first_author="Alma", year=2024, short_title="Phenotypic plasticity and carryover in an ecologically important bivalve",
         species="NR", common_name="NR", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="veliger-larva", life_stage_assayed="spat-juvenile",
         priming_window_text="changing-environment exposures with carryover assays",
         stressor_category="multiple", stressor_specific="changing environments (plasticity + carryover)",
         environmentally_realistic="yes",
         assay_type="physiology-other", outcome_metric="phenotypic plasticity and carryover effects",
         effect_direction="mixed", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="yes",
         methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="environmental change with carryover design", extraction_confidence="low",
         notes="species to confirm on full text (Front. Mar. Sci. 2024)"),
    dict(record_id="kozal2024-01", study_key="kozal2024", doi="10.3354/aei00472",
         first_author="Kozal", year=2024, short_title="Paternal heat exposure affects green-lipped mussel progeny",
         species="Perna canaliculus", common_name="green-lipped mussel", taxon_group="bivalve", taxon_class="Bivalvia",
         generation_primed="F0", generation_assayed="F1", transmission_channel="paternal",
         life_stage_primed="gamete-broodstock", life_stage_assayed="veliger-larva",
         priming_window_text="paternal heat exposure prior to spawning",
         stressor_category="thermal", stressor_specific="paternal heat exposure",
         environmentally_realistic="yes",
         assay_type="growth-size", outcome_metric="progeny larval development",
         effect_direction="mixed", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="not-tested", methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="paternal thermal conditioning; larval assays", extraction_confidence="med"),
    dict(record_id="glass2023-01", study_key="glass2023", doi="10.7717/peerj.16574",
         first_author="Glass", year=2023, short_title="Acute heat priming promotes short-term climate resilience in sea anemone early life",
         species="Exaiptasia diaphana", common_name="model sea anemone", taxon_group="coral", taxon_class="Anthozoa",
         generation_primed="F0", generation_assayed="F0", transmission_channel="somatic-within-gen",
         life_stage_primed="embryo", life_stage_assayed="spat-juvenile",
         priming_window_text="acute heat priming of early life stages",
         stressor_category="thermal", stressor_specific="acute heat priming",
         environmentally_realistic="yes",
         assay_type="survival", outcome_metric="short-term climate resilience of early life stages",
         effect_direction="beneficial", effect_size_type="NR", significance="sig",
         persistence_unit="days", persisted_past_metamorphosis="not-tested",
         persistence_notes="short-term within early life; persistence limited",
         methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="acute heat prime then stress challenge", extraction_confidence="med",
         notes="anemone as anthozoan model; taxon_group=coral for filter bucket"),
    dict(record_id="fellous2022-01", study_key="fellous2022", doi="10.1111/gcb.15912",
         first_author="Fellous", year=2022, short_title="Warming windows reshape epigenetic reprogramming across stickleback gametogenesis/embryogenesis",
         species="Gasterosteus aculeatus", common_name="three-spined stickleback", taxon_group="fish", taxon_class="Actinopterygii",
         generation_primed="F0", generation_assayed="F1", transmission_channel="biparental",
         life_stage_primed="gamete-broodstock", life_stage_assayed="embryo",
         priming_window_text="ocean warming across gametogenesis and embryogenesis windows",
         stressor_category="thermal", stressor_specific="ocean warming",
         environmentally_realistic="yes",
         assay_type="methylation", outcome_metric="temperature-sensitive epigenetic reprogramming and gene expression",
         effect_direction="mixed", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="NA",
         methylation_measured="yes", methylation_method="other", transcriptome_measured="yes", ncRNA_measured="no",
         study_design="factorial warming windows across reproductive/developmental stages",
         extraction_confidence="med"),
    dict(record_id="waite2022-01", study_key="waite2022", doi="10.1002/ecy.3565",
         first_author="Waite", year=2022, short_title="Negative carry-over effects on larval thermal tolerances",
         species="NR", common_name="NR", taxon_group="other", taxon_class="NR",
         generation_primed="F0", generation_assayed="F1", transmission_channel="unclear",
         life_stage_primed="adult", life_stage_assayed="veliger-larva",
         priming_window_text="natural thermal gradient parental/developmental environments",
         stressor_category="thermal", stressor_specific="natural thermal gradient carryover",
         environmentally_realistic="yes",
         assay_type="physiology-other", outcome_metric="larval thermal tolerance (negative carryover)",
         effect_direction="costly", effect_size_type="NR", significance="sig",
         persisted_past_metamorphosis="not-tested", methylation_measured="no", transcriptome_measured="no", ncRNA_measured="no",
         study_design="natural gradient carryover on larval thermal tolerance", extraction_confidence="low",
         notes="species/system to confirm on full text"),
]


def cols() -> list[str]:
    with open(VOCAB) as fh:
        return [c["name"] for c in yaml.safe_load(fh)["columns"]]


def upsert_screening() -> int:
    rows = list(csv.DictReader(open(SCREEN))) if SCREEN.exists() else []
    by_doi = {
        r["doi"].lower(): r for r in rows
        if r.get("doi") and r["doi"] not in ("NR", "xx.xxxx/placeholder")
    }
    by_key = {r["record_key"]: r for r in rows}

    added = 0
    for b in BIBLIO:
        doi = b["doi"]
        key = b["key"]
        if key in by_key:
            continue
        if doi not in ("NR", "xx.xxxx/placeholder") and doi.lower() in by_doi:
            continue

        row = {
            "record_key": key,
            "doi": doi,
            "first_author": b["author"],
            "year": b["year"],
            "title": b["title"],
            "source": SRC,
            "decision": b["decision"],
            "exclude_reason": b.get("reason", ""),
            "maps_to_study_key": key if b["decision"] == "include" else "",
            "screened_by": "user-bibliography",
            "notes": b.get("notes", ""),
        }
        rows.append(row)
        by_key[key] = row
        if doi not in ("NR", "xx.xxxx/placeholder"):
            by_doi[doi.lower()] = row
        added += 1

    with open(SCREEN, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=SCREEN_FIELDS, extrasaction="ignore")
        w.writeheader()
        for r in rows:
            w.writerow({k: r.get(k, "") for k in SCREEN_FIELDS})
    return added


def append_extractions() -> int:
    columns = cols()
    existing = list(csv.DictReader(open(ATLAS))) if ATLAS.exists() else []
    ids = {r["record_id"] for r in existing}
    added = 0
    for row in EXTRACT:
        if row["record_id"] in ids:
            continue
        full = {c: "" for c in columns}
        full.update(row)
        full["extractor"] = row.get("extractor") or EX
        full["extraction_date"] = row.get("extraction_date") or TODAY
        if not full.get("source_location"):
            full["source_location"] = "user bibliography + title/abstract"
        existing.append(full)
        ids.add(row["record_id"])
        added += 1

    with open(ATLAS, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=columns)
        w.writeheader()
        w.writerows(existing)
    return added


def main() -> int:
    n_screen = upsert_screening()
    n_atlas = append_extractions()
    print(f"screening: +{n_screen} bibliography records")
    print(f"atlas: +{n_atlas} new contrasts")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
